### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by overlookmotel** [TimBeyer/cls-bluebird#10]
Hi @TimBeyer.

Thanks loads for making me a contributor. I'll aim to do you proud!

Could you possibly enable [Travis](https://travis-ci.org/TimBeyer/cls-bluebird) for this repo? I can't do it - it seems only the repo owner can.

I'd like to run the tests against different versions of node, and it's also useful to have the test result history public, and see if any PRs break the tests.

I see you have a Travis account, so it should be as easy as going to https://travis-ci.org/TimBeyer/cls-bluebird and clicking "Activate repository".

**Comment by overlookmotel** [comment]
By the way, I've done a couple of releases to close 2 open PRs about peer dependencies.

Would you prefer I post changes as PRs for you to review, or are you happy for me to just commit away (obeying semver, obviously)? I'm easy either way - whichever you prefer.

**Comment by TimBeyer** [comment]
Done. For changes I usually prefer PRs.
I also PR things even if I'm the only person working on something.
Makes it easier for people to see what changed when and makes it easier for you to review your own code as well.
