### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by CrazyBS** [TimBeyer/cls-bluebird#16]
I'd like to use this library, but I can't legally use it unless it has a LICENSE file in it.  I don't suppose you folks can add that in so I can cross off my red box?

**Comment by vdeturckheim** [comment]
You have a license claim in the package.json https://github.com/TimBeyer/cls-bluebird/blob/master/package.json#L38

**Comment by overlookmotel** [comment]
@CrazyBS What @vdeturckheim says is correct. The license as stated in `package.json` is BSD-2. This is also noted on the [NPM page for the module](https://www.npmjs.com/package/cls-bluebird).

I'm going to close this issue. Please comment again if this doesn't satisfy your needs.
