### ISSUE TITLE
cls and promisify

### ISSUE THREAD

**Issue by matteogrolla** [TimBeyer/cls-bluebird#19]
Hi Tim,
            I'm having troubles using async/await and cls on a library that has been promisified with bluebird.
The particular library is
https://github.com/maxlath/nano-blue2
but maybe the solution is valid in general.

Can you please point me in the right direction?
Thanks a lot!

**Comment by overlookmotel** [comment]
Can you be a little more specific about what you mean by "having troubles" please?

**Comment by overlookmotel** [comment]
Closing this issue as it's been a long time and no further info provided by the OP.
