### ISSUE TITLE
how to run test?

### ISSUE THREAD

**Issue by RobinQu** [TimBeyer/cls-bluebird#5]
I'd like to submit a patch to fix cls with `Promise.coroutine`. However, regression cannot be done because I cannot run unit tests.

`npm test` seemed to have no response until I sent SIGINT.

Of course, I already had a redis instance running at localhost:6379.

**Comment by overlookmotel** [comment]
@RobinQu I'm working on re-writing the tests to remove the `redis` dependency, and am also aiming to fix any bugs in `cls-bluebird` that I find, and extend support to bluebird v3. `Promise.coroutine` is a particular interest to me as I use coroutines a lot.

Can you tell me what bug you found and post the patch that you had in mind?

**Comment by overlookmotel** [comment]
Ping @RobinQu
