### ISSUE TITLE
Not working with bluebird v3

### ISSUE THREAD

**Issue by overlookmotel** [TimBeyer/cls-bluebird#8]
Raising this issue more to warn others than anything else at this point.

`cls-bluebird` does not currently work with `bluebird` v3.

There are at least a couple of problems:
1. The `progress` argument has been removed from `_addHandlers()` in bluebird v3
2. When calling `.then()` on promise which is already resolved, `_addHandlers()` is not called in bluebird v3

I'm working on fixing this, but at present best to avoid using this module with bluebird versions later than 2.x.x

**Comment by Jeff-Lewis** [comment]
@overlookmotel Thanks for picking up cls-bluebird. In order to bring it up to speed with Bluebird v3, will it be similar to what [Sequelize does](https://github.com/sequelize/sequelize/blob/e46c0007b6b1e689fcb84b9df3f7150492a4c49e/lib/promise.js)?

**Comment by overlookmotel** [comment]
@Jeff-Lewis I'm looking to patch a couple of internal Bluebird functions which are called by all public methods, rather than patch every Bluebird method individually as Sequelize does.

Actually, the aim is to move Sequelize over to `cls-bluebird` once this work is complete.

I'm not 100% sure that Sequelize's shim works completely in all cases. I've had occasional CLS context loss in some weird edge cases with Sequelize's shim (though there were other moving parts involved, so can't conclusively say that it's a problem with Sequelize).

The main thing actually is to write a comprehensive test suite to make sure it's 100% bullet-proof, and I'm on the case with that now.

**Comment by ravivaxonite** [comment]
hey ,
when do you think it will be published ? 
it will help my very much

**Comment by overlookmotel** [comment]
@ravivaxonite Can't really give a prediction I'm afraid. It's complicated stuff and I have other work going on which is unpredictable.

**Comment by ravivaxonite** [comment]
dont looking for a commit  :)
some assumption   ?

**Comment by overlookmotel** [comment]
Maybe a month. But I make no promises! (no pun intended)

**Comment by overlookmotel** [comment]
@Jeff-Lewis I've changed my mind! I am now proposing to adopt a patch similar to Sequelize's. See #13.

**Comment by overlookmotel** [comment]
Fixed in v2.0.0
