### ISSUE TITLE
Re-write of tests

### ISSUE THREAD

**Issue by overlookmotel** [TimBeyer/cls-bluebird#9]
Hi @TimBeyer.

Would you likely accept a PR completely rewriting the tests? Here's what I have in mind:
- using `mocha`
- removing the `redis` dependency (using [lose-cls-context](https://www.npmjs.com/package/lose-cls-context) instead)
- testing against both bluebird v2 and v3
- testing every conceivable combination of methods and circumstances (including those mentioned as potentially problematic in #1)

Apologies for the sudden torrent of issues! [Sequelize](https://www.npmjs.com/package/sequelize) is switching to using co-routines internally and I want to take this opportunity to move it over to using `cls-bluebird` for its CLS support. But we need to make sure it's as robust as possible as CLS maintains transactions in Sequelize and so is completely critical to ensuring data consistency in the database. Hence a desire to really flesh out the tests to cover all possible cases.

I'm happy to do a lot of legwork myself on this (and it will be quite an effort). But just want to make sure you're going to be willing and have time to review PRs.

**Comment by TimBeyer** [comment]
Hey @overlookmotel, since you constantly put so much effort in describing issues and contributing, I made you a contributor. I also gave you permission to publish on npm.
I'll gladly take a look at your PRs too. Thanks for all the hard work you put into explaining the issues and helping out.

**Comment by overlookmotel** [comment]
New test suite written and submitted as PR #15.

**Comment by overlookmotel** [comment]
Released in v2.0.0
